/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as TournamentsTournamentIdRouteImport } from './routes/tournaments_.$tournamentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/tournaments_/$tournamentId',
  path: '/tournaments/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tournaments': typeof TournamentsRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tournaments': typeof TournamentsRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tournaments': typeof TournamentsRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/tournaments_/$tournamentId': typeof TournamentsTournamentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/tournaments' | '/boards/$boardId' | '/tournaments/$tournamentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tournaments' | '/boards/$boardId' | '/tournaments/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/tournaments'
    | '/boards/$boardId'
    | '/tournaments_/$tournamentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TournamentsRoute: typeof TournamentsRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments_/$tournamentId': {
      id: '/tournaments_/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TournamentsRoute: TournamentsRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  TournamentsTournamentIdRoute: TournamentsTournamentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
